name: Run tests
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Intall tox
        run: |

          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests with tox
        run: tox -e test
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Intall tox
        run: |

          python -m pip install --upgrade pip
          pip install tox
      - name: Typing
        run: tox -e type
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Intall tox
        run: |

          python -m pip install --upgrade pip
          pip install tox
      - name: Linting
        run: tox -e lint
